/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { WorkEntry, VacationYear, UserSettings, SavedObject, TarifvertragLevel, RosterShift } from '../types';

export const INITIAL_USER_SETTINGS: UserSettings = {
  employeeName: 'Maik Hoyer',
  defaultLocation: 'Objekt 102 - IKEA Tempelhof',
  objektKostenstelle: 'Kostenstelle 44-A (IKEA Tempelhof)',
  hourlyWage: 17.50, // 17.50 € / Stunde
  taxClass: 1, // Steuerklasse 1
  childrenCount: 1, // 1 Kind
  hasChurchTax: false, // Keine Kirche
  healthInsurance: 'IKK Berlin/Brandenburg', // IKK BB Zusatzbeitrag ist in Rechner integriert
  isBreakPaid: true, // Bezahlte Pausenzeiten standardmäßig aktiviert
};

export const INITIAL_TARIFF_LEVELS: TarifvertragLevel[] = [
  { id: 'tarif-1', name: 'Lohngruppe 1 (Einstieg / Hilfstätigkeit)', hourlyWage: 14.50 },
  { id: 'tarif-2', name: 'Lohngruppe 2 (Angelernte Kraft)', hourlyWage: 15.80 },
  { id: 'tarif-3', name: 'Lohngruppe 3 (Fachkraft / Geselle)', hourlyWage: 17.50 },
  { id: 'tarif-4', name: 'Lohngruppe 4 (Spezialist / Vorarbeiter)', hourlyWage: 20.20 },
  { id: 'tarif-5', name: 'Lohngruppe 5 (Meister / Bauleiter)', hourlyWage: 23.50 },
];

export const INITIAL_SAVED_OBJECTS: SavedObject[] = [
  {
    id: 'obj-1',
    name: 'Objekt 102 - IKEA Tempelhof',
    distanceKm: 28,
    travelTimeMinutes: 40,
    hourlyWage: 17.50,
    tariffLevelId: 'tarif-3',
  },
  {
    id: 'obj-2',
    name: 'Objekt 208 - Potsdam West',
    distanceKm: 52,
    travelTimeMinutes: 65,
    hourlyWage: 20.20,
    tariffLevelId: 'tarif-4',
  },
  {
    id: 'obj-3',
    name: 'Objekt 301 - Berlin Mitte',
    distanceKm: 12,
    travelTimeMinutes: 25,
    hourlyWage: 14.50,
    tariffLevelId: 'tarif-1',
  },
];

export const INITIAL_VACATION_ALOCATION: VacationYear[] = [
  { year: 2025, entitlement: 30 },
  { year: 2026, entitlement: 30 },
];

export const INITIAL_WORK_ENTRIES: WorkEntry[] = [
  {
    id: 'seed-feiertag-1',
    date: '2026-06-01', // Pfingstmontag 2026
    type: 'Feiertag',
    location: 'Pfingstmontag - Gesetzlicher Feiertag',
    startTime: '',
    endTime: '',
    breakMinutes: 0,
    travelTimeMinutes: 0,
    travelDistanceKm: 0,
    notes: 'Gesetzlicher Feiertag (Lohnfortzahlung)',
  },
  {
    id: 'seed-work-1',
    date: '2026-06-02',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:15',
    breakMinutes: 45, // 0.75 Stunden
    travelTimeMinutes: 40,
    travelDistanceKm: 28,
    notes: 'Kabelzugarbeiten Etage 1',
  },
  {
    id: 'seed-work-2',
    date: '2026-06-03',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:30',
    breakMinutes: 45,
    travelTimeMinutes: 40,
    travelDistanceKm: 28,
    notes: 'Kabelkanäle montiert und beschriftet',
  },
  {
    id: 'seed-work-3',
    date: '2026-06-04',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:00',
    breakMinutes: 30,
    travelTimeMinutes: 40,
    travelDistanceKm: 28,
    notes: 'Dosen gesetzt und angeschlossen',
  },
  {
    id: 'seed-work-4',
    date: '2026-06-05',
    type: 'Arbeit',
    location: 'Objekt 208 - Potsdam West',
    startTime: '08:00',
    endTime: '16:30',
    breakMinutes: 30,
    travelTimeMinutes: 65,
    travelDistanceKm: 52,
    notes: 'Auswärtiger Baustellentermin',
  },
  {
    id: 'seed-urlaub-1',
    date: '2026-06-08',
    type: 'Urlaub',
    location: '🌴 Erholungsurlaub Sommer',
    startTime: '',
    endTime: '',
    breakMinutes: 0,
    travelTimeMinutes: 0,
    travelDistanceKm: 0,
    notes: 'Genehmigter Jahresurlaub',
  },
  {
    id: 'seed-urlaub-2',
    date: '2026-06-09',
    type: 'Urlaub',
    location: '🌴 Erholungsurlaub Sommer',
    startTime: '',
    endTime: '',
    breakMinutes: 0,
    travelTimeMinutes: 0,
    travelDistanceKm: 0,
    notes: 'Genehmigter Jahresurlaub',
  },
  {
    id: 'seed-urlaub-3',
    date: '2026-06-10',
    type: 'Urlaub',
    location: '🌴 Erholungsurlaub Sommer',
    startTime: '',
    endTime: '',
    breakMinutes: 0,
    travelTimeMinutes: 0,
    travelDistanceKm: 0,
    notes: 'Genehmigter Jahresurlaub',
  },
  {
    id: 'seed-urlaub-4',
    date: '2026-06-11',
    type: 'Urlaub',
    location: '🌴 Erholungsurlaub Sommer',
    startTime: '',
    endTime: '',
    breakMinutes: 0,
    travelTimeMinutes: 0,
    travelDistanceKm: 0,
    notes: 'Genehmigter Jahresurlaub',
  },
  {
    id: 'seed-urlaub-5',
    date: '2026-06-12',
    type: 'Urlaub',
    location: '🌴 Erholungsurlaub Sommer',
    startTime: '',
    endTime: '',
    breakMinutes: 0,
    travelTimeMinutes: 0,
    travelDistanceKm: 0,
    notes: 'Genehmigter Jahresurlaub',
  },
  {
    id: 'seed-krank-1',
    date: '2026-06-15',
    type: 'Krank',
    location: '🤒 Arbeitsunfähigkeit (AU)',
    startTime: '',
    endTime: '',
    breakMinutes: 0,
    travelTimeMinutes: 0,
    travelDistanceKm: 0,
    notes: 'Krankmeldung per AU eingereicht',
  },
  {
    id: 'seed-work-5',
    date: '2026-06-16',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '17:00',
    breakMinutes: 45,
    travelTimeMinutes: 40,
    travelDistanceKm: 28,
    notes: 'Schaltschrank-Verdrahtung',
  },
  {
    id: 'seed-work-6',
    date: '2026-06-17',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:15',
    breakMinutes: 30,
    travelTimeMinutes: 40,
    travelDistanceKm: 28,
  },
  {
    id: 'seed-work-7',
    date: '2026-06-18',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:00',
    breakMinutes: 30,
    travelTimeMinutes: 40,
    travelDistanceKm: 28,
  },
  {
    id: 'seed-work-8',
    date: '2026-06-19',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '15:15',
    breakMinutes: 30,
    travelTimeMinutes: 40,
    travelDistanceKm: 28,
    notes: 'Wochenbericht fertiggestellt',
  },
];

export const INITIAL_ROSTER_SHIFTS: RosterShift[] = [
  {
    id: 'roster-1',
    date: '2026-07-01',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:00',
    breakMinutes: 30,
    notes: 'Geplante Frühschicht',
  },
  {
    id: 'roster-2',
    date: '2026-07-02',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:00',
    breakMinutes: 30,
    notes: 'Geplante Frühschicht',
  },
  {
    id: 'roster-3',
    date: '2026-07-03',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:00',
    breakMinutes: 30,
    notes: 'Frühschicht vor dem Wochenende',
  },
  {
    id: 'roster-4',
    date: '2026-07-06',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:00',
    breakMinutes: 30,
  },
  {
    id: 'roster-5',
    date: '2026-07-07',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:00',
    breakMinutes: 30,
  },
  {
    id: 'roster-6',
    date: '2026-07-08',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:00',
    breakMinutes: 30,
  },
  {
    id: 'roster-7',
    date: '2026-07-09',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:00',
    breakMinutes: 30,
  },
  {
    id: 'roster-8',
    date: '2026-07-10',
    type: 'Arbeit',
    location: 'Objekt 102 - IKEA Tempelhof',
    startTime: '07:30',
    endTime: '16:00',
    breakMinutes: 30,
  },
  {
    id: 'roster-9',
    date: '2026-07-13',
    type: 'Arbeit',
    location: 'Anderer Einsatzort',
    startTime: '08:00',
    endTime: '16:30',
    breakMinutes: 30,
    notes: 'Sonderdienst',
  },
  {
    id: 'roster-10',
    date: '2026-07-14',
    type: 'Arbeit',
    location: 'Anderer Einsatzort',
    startTime: '08:00',
    endTime: '16:30',
    breakMinutes: 30,
    notes: 'Sonderdienst',
  },
];

